trigger:
  - platform: state
    entity_id: ['sensor.kaipule_technology_co_ltd_im20_door_window_sensor_access_control','sensor.kaipule_technology_co_ltd_im20_door_window_sensor_access_control_2','sensor.kaipule_technology_co_ltd_im20_door_window_sensor_access_control_3','sensor.kaipule_technology_co_ltd_im20_door_window_sensor_access_control_4']
    from: '23'
    to: '22'
condition:
  condition: and
  conditions: 
    - condition: time
      after: '07:00:00'
      before: '23:00:00'
action:
  - service: scene.turn_on
    entity_id: scene.heating_off
  - service: persistent_notification.create
    data:
      message: '{{ now().strftime("%H:%M") }} AUS: Heizung'
      title: "Heizung"
