trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.laundry
action:
  - service: persistent_notification.create
    data:
      message: "Fertig!"
      title: "Wäsche"
  - service: notify.notify
    data:
      message: "Wäsche ist fertig"
