trigger:
  - event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad
      scene_id: 2
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
action:
  - service: scene.turn_on
    entity_id: scene.heating_off
  - service: persistent_notification.create
    data:
      message: 'AUS {{ now().strftime("%H:%M") }}'
      title: "Heizung"
