trigger:
  - event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad
      scene_id: 4
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
action:
  - service: light.toggle
    data:
      entity_id: light.aeotec_limited_zwa002_led_bulb_6_multi_color_level
