trigger:
  - event_data:
      entity_id: zwave.aeon_labs_zw130_wallmote_quad
      scene_id: 3
      scene_data: 0
    event_type: zwave.scene_activated
    platform: event
action:
  - service: timer.start
    entity_id: timer.laundry
  - service: persistent_notification.create
    data:
      message: "Timer für Waschmaschine läuft"
      title: "Wäsche"
  - service: notify.notify
    data:
      message: "Timer für Waschmaschine läuft"
