# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# MariaDB
recorder:
  db_url: !secret maria_db

# Monitor
sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: processor_temperature
      - type: memory_free
      - type: disk_use_percent
        arg: /
      - type: disk_use
      - type: disk_free

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml