homeassistant:
  customize: !include customize.yaml

default_config:
tts:
- platform: google_translate
zwave:
  usb_path: /dev/ttyACM0
binary_sensor:
- platform: workday
  country: DE
  province: BY
device_tracker:
- platform: ping
  interval_seconds: 200
  consider_home: 400
  hosts:
    thomas_handy:
    kathi_handy:
logger:
  default: critical
  #default: info
  logs:
    homeassistant.components.yamaha: critical
    custom_components.my_integration: critical
timer:
  laundry:
    duration: '02:00:00'
    icon: 'mdi:washing-machine'
automation: !include_dir_list automations
scene: !include scenes.yaml

group: !include groups.yaml
script: !include scripts.yaml
