kathi_handy:
  hide_if_away: false
  icon:
  mac:
  name: Kathi
  picture:
  track: true
  
thomas_handy:
  hide_if_away: false
  icon:
  mac:
  name: Thomas
  picture:
  track: true
  
thomas_pc:
  hide_if_away: false
  icon:
  mac:
  name: HARDCOREHOLLY
  picture:
  track: true
