### SCENES

### TURN HEATING ON
- name: heating_on
  entities:
    climate.thermostat_wohnzimmer_heating_1:
      state: on
      temperature: 20
      min_temp: 20
      max_temp: 21
    climate.thermostat_schlafzimmer_heating_1_2:
      state: on
      temperature: 20
      min_temp: 20
      max_temp: 21
    climate.thermmostat_bad_heating_1_3:
      state: on
      temperature: 20
      min_temp: 20
      max_temp: 21
    #climate.thermostat_kche_heating_1_4:
      #state: on
      #temperature: 20
      #min_temp: 20
      #max_temp: 21

### TURN HEATING OFF
- name: heating_off
  entities:
    climate.thermostat_wohnzimmer_heating_1:
      state: on
      temperature: 14
      min_temp: 13
      max_temp: 15
    climate.thermostat_schlafzimmer_heating_1_2:
      state: on
      temperature: 14
      min_temp: 13
      max_temp: 15
    climate.thermmostat_bad_heating_1_3:
      state: on
      temperature: 14
      min_temp: 13
      max_temp: 15
    climate.thermostat_kche_heating_1_4:
      state: on
      temperature: 14
      min_temp: 13
      max_temp: 15

### NACHTABSENKUNG
- name: heating_at_night
  entities:
    climate.thermostat_wohnzimmer_heating_1:
      state: on
      temperature: 18
      min_temp: 17
      max_temp: 19
    climate.thermostat_schlafzimmer_heating_1_2:
      state: on
      temperature: 21
      min_temp: 20
      max_temp: 22
    climate.thermmostat_bad_heating_1_3:
      state: on
      temperature: 18
      min_temp: 17
      max_temp: 19
    #climate.thermostat_kche_heating_1_4:
      #state: on
      #temperature: 18
      #min_temp: 17
      #max_temp: 19
